### PR TITLE
[suggestions] Add forced floating label to props

### PR DESCRIPTION
**Pull request by vlntsolo**
Handy for displaying values all the time or for inactive range element.

### CODE REVIEW

**Comment by simeydotme** [comment]
This is something a Frontend Developer should realise is a job for CSS, as written here; https://github.com/simeydotme/svelte-range-slider-pips#styling :)
https://svelte.dev/repl/23b0806809a84908921034949125b4b3?version=3.44.1

**Comment by simeydotme** [comment]
even if this wasn't possible with CSS, I'd suggest re-considering modifying properties on mount, it seems like a code-smell, or hacky way to do things inside of a component.

**Comment by vlntsolo** [comment]
@simeydotme , Thanks for the REPL. I should have better opened an issue and ask before creating this useless pull request. Don't know what was on my mind. Thanks again for the component.

**Comment by simeydotme** [comment]
haha, no problem!
hope it's working well for you! :)

**Pull request closed without merging**
